# Generated by Django 3.0.3 on 2020-11-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20201116_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicecommand',
            name='CmdTime',
            field=models.CharField(max_length=15),
        ),
    ]
